# This is autogenerated file from Sparx Enterprise Application Catalogue
#



UB = softwareSystem "UB" {
   description "Unified balance"
   tags "landscape" "cmdb:UB" "status:В резерве"
}
SEDO = softwareSystem "SEDO" {
   description "Система электронного документооборота"
   tags "landscape" "cmdb:SEDO" "status:Proposed"
}
PRS = softwareSystem "PRS" {
   description "Predict Service"
   tags "landscape" "cmdb:PRS" "status:Proposed"
}
