@startuml Billing Data Model

entity Invoice {
    * innvoice_id integer
    * client_id integer
    --
    amount integer
    tax integer
    data datetime
}

entity Client {
    * client_id integer
    --
    address varchar(4096)
}

entity Payment {
    * payment_id integer
    --
    amount integer
}

entity Usage {
    * usage_id integer
    --
    * invoice_id integer
    * payment_id integer
}

Invoice }|-- Payment
Invoice }|-- Client
Usage }-- Invoice
Usage --|{ Payment

@enduml