version: '3.3'
services:
  structurizr:
    image: structurizr/lite
    container_name: structurizr_lite
    depends_on:
      - structurizr-onpremises
    ports:
      - 8080:8080
    volumes:
        - .:/usr/local/structurizr:z

  structurizr-onpremises:
    image: structurizr/onpremises
    container_name: structurizr-onpremises
    ports:
      - 8081:8080
    volumes:
        - ./onpremises:/usr/local/structurizr
  plantuml-server:
    image: plantuml/plantuml-server:tomcat
    container_name: plantuml-server
    ports:
      - 8082:8080
    environment:
      - BASE_URL=plantuml

  db:
    image: postgres
    restart: always
    volumes:
      - db-volume:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
volumes:
  db-volume: