resources:

  - id: "1"
    name: "Пользователь"
    subtitle: "[Person]"
    description: "Заказчик услуги, осуществляющий наблюдение за ребенком"
    backgroundColor: "#08427b"
    color: "#ffffff"

  - id: "2"
    name: "Внешняя платежная система"
    subtitle: "[Software System]"
    description: "Регистрация платежей за сервис"
    backgroundColor: "#c0c0c0"
    color: "#ffffff"

  - id: "3"
    name: "Дрон"
    subtitle: "[Software System]"
    description: "Автономный дрон"
    backgroundColor: "#c0c0c0"
    color: "#ffffff"

  - id: "4"
    name: "ЧОП"
    subtitle: "[Software System]"
    description: "Внешнее партнерское охранное агенство"
    backgroundColor: "#c0c0c0"
    color: "#ffffff"

  - id: "5"
    name: "Мобильный телохранитель"
    subtitle: "[Software System]"
    backgroundColor: "#dddddd"
    color: "#000000"

    children:
      - id: "11"
        name: "Backend мобильного приложения клиента"
        subtitle: "[Container: go]"
        description: "Приложение для осуществления заказа услуги и контроля передвижения"
        backgroundColor: "#438dd5"
        color: "#ffffff"

      - id: "12"
        name: "Backend веб приложения клиента"
        subtitle: "[Container: go]"
        description: "Приложение для осуществления заказа услуги и контроля передвижения"
        backgroundColor: "#438dd5"
        color: "#ffffff"

      - id: "15"
        name: "Single Sign On"
        subtitle: "[Container: KeyCloak]"
        description: "Аутентификация и авторизация пользователей"
        backgroundColor: "#438dd5"
        color: "#ffffff"

      - id: "18"
        name: "BPM"
        subtitle: "[Container: Camunda]"
        description: "Реализация сценариев трэкинга"
        backgroundColor: "#438dd5"
        color: "#ffffff"

      - id: "21"
        name: "Billing"
        subtitle: "[Container: go]"
        description: "Прием оплат и контроль расходов"
        backgroundColor: "#438dd5"
        color: "#ffffff"

        children:
          - id: "22"
            name: "API"
            subtitle: "[Component: go]"
            description: "Интерфейс для работы с подписками"
            backgroundColor: "#85bbf0"
            color: "#000000"

          - id: "23"
            name: "Subscription Database"
            subtitle: "[Component: PostgreSQL]"
            description: "Информация о балансах"
            backgroundColor: "#85bbf0"
            color: "#000000"

          - id: "24"
            name: "Controler"
            subtitle: "[Component: go]"
            description: "Сервис учета использования дронов"
            backgroundColor: "#85bbf0"
            color: "#000000"

          - id: "25"
            name: "Брокер"
            subtitle: "[Component: RabbitMQ/MQTT]"
            description: "Брокер для учета использования дронов"
            backgroundColor: "#85bbf0"
            color: "#000000"

          - id: "26"
            name: "Шлюз"
            subtitle: "[Component]"
            backgroundColor: "#85bbf0"
            color: "#000000"

      - id: "38"
        name: "Inventory"
        subtitle: "[Container: go]"
        description: "Учет дронов"
        backgroundColor: "#438dd5"
        color: "#ffffff"

        children:
          - id: "39"
            name: "API"
            subtitle: "[Component: REST]"
            description: "API учета информации о дронах"
            backgroundColor: "#85bbf0"
            color: "#000000"

          - id: "40"
            name: "Реестр дронов"
            subtitle: "[Component: PosthreSQL]"
            description: "Учет информации о дронах"
            backgroundColor: "#85bbf0"
            color: "#000000"

      - id: "44"
        name: "Clients"
        subtitle: "[Container: go]"
        description: "Учет пользователей"
        backgroundColor: "#438dd5"
        color: "#ffffff"

        children:
          - id: "45"
            name: "API"
            subtitle: "[Component: REST]"
            description: "Интерфейс для работы с клиентом"
            backgroundColor: "#85bbf0"
            color: "#000000"

          - id: "46"
            name: "Client Database"
            subtitle: "[Component: PostgreSQL]"
            description: "Информация о клиентах"
            backgroundColor: "#85bbf0"
            color: "#000000"

      - id: "53"
        name: "Tracker"
        subtitle: "[Container: go]"
        description: "Подсистема трэкинга дронов в реальном времени"
        backgroundColor: "#438dd5"
        color: "#ffffff"

        children:
          - id: "54"
            name: "API"
            subtitle: "[Component: REST]"
            description: "Интерфейс для работы с дронами"
            backgroundColor: "#85bbf0"
            color: "#000000"

          - id: "55"
            name: "Данные дронов"
            subtitle: "[Component: Redis]"
            description: "Информация о позиции и данных дронов"
            backgroundColor: "#85bbf0"
            color: "#000000"

          - id: "56"
            name: "Брокер"
            subtitle: "[Component: RabbitMQ/MQTT]"
            description: "Брокер для взаимодействия с дронами"
            backgroundColor: "#85bbf0"
            color: "#000000"

          - id: "57"
            name: "Controler"
            subtitle: "[Component: go]"
            description: "Сервис управления дронами"
            backgroundColor: "#85bbf0"
            color: "#000000"

      - id: "6"
        name: "Мобильное приложение клиента"
        subtitle: "[Container: Android/iOS app]"
        description: "Приложение для осуществления заказа услуги и контроля передвижения"
        backgroundColor: "#438dd5"
        color: "#ffffff"

      - id: "7"
        name: "Веб приложение клиента"
        subtitle: "[Container: Web Browser]"
        description: "Приложение для осуществления заказа услуги и контроля передвижения"
        backgroundColor: "#438dd5"
        color: "#ffffff"

  - id: "101"
    name: "DroneNodeN"
    subtitle: "[Deployment Node]"
    backgroundColor: "#ffffff"
    color: "#000000"

    children:
      - id: "102"
        name: "Дрон"
        subtitle: "[Software System]"
        description: "Автономный дрон"
        backgroundColor: "#c0c0c0"
        color: "#ffffff"

  - id: "105"
    name: "SecurityNode1"
    subtitle: "[Deployment Node]"
    backgroundColor: "#ffffff"
    color: "#000000"

    children:
      - id: "106"
        name: "ЧОП"
        subtitle: "[Software System]"
        description: "Внешнее партнерское охранное агенство"
        backgroundColor: "#c0c0c0"
        color: "#ffffff"

  - id: "108"
    name: "PaymentNode1"
    subtitle: "[Deployment Node]"
    backgroundColor: "#ffffff"
    color: "#000000"

    children:
      - id: "109"
        name: "Внешняя платежная система"
        subtitle: "[Software System]"
        description: "Регистрация платежей за сервис"
        backgroundColor: "#c0c0c0"
        color: "#ffffff"

  - id: "112"
    name: "Client Device 1"
    subtitle: "[Deployment Node]"
    backgroundColor: "#ffffff"
    color: "#000000"

    children:
      - id: "113"
        name: "Мобильное приложение клиента"
        subtitle: "[Container: Android/iOS app]"
        description: "Приложение для осуществления заказа услуги и контроля передвижения"
        backgroundColor: "#438dd5"
        color: "#ffffff"

  - id: "114"
    name: "Client Device 2"
    subtitle: "[Deployment Node]"
    backgroundColor: "#ffffff"
    color: "#000000"

    children:
      - id: "115"
        name: "Веб приложение клиента"
        subtitle: "[Container: Web Browser]"
        description: "Приложение для осуществления заказа услуги и контроля передвижения"
        backgroundColor: "#438dd5"
        color: "#ffffff"

  - id: "116"
    name: "BFF Server Mobile"
    subtitle: "[Deployment Node]"
    backgroundColor: "#ffffff"
    color: "#000000"

    children:
      - id: "117"
        name: "Backend мобильного приложения клиента"
        subtitle: "[Container: go]"
        description: "Приложение для осуществления заказа услуги и контроля передвижения"
        backgroundColor: "#438dd5"
        color: "#ffffff"

  - id: "119"
    name: "BFF Server Web"
    subtitle: "[Deployment Node]"
    backgroundColor: "#ffffff"
    color: "#000000"

    children:
      - id: "120"
        name: "Backend веб приложения клиента"
        subtitle: "[Container: go]"
        description: "Приложение для осуществления заказа услуги и контроля передвижения"
        backgroundColor: "#438dd5"
        color: "#ffffff"

  - id: "122"
    name: "BPM First"
    subtitle: "[Deployment Node]"
    backgroundColor: "#ffffff"
    color: "#000000"

    children:
      - id: "123"
        name: "BPM"
        subtitle: "[Container: Camunda]"
        description: "Реализация сценариев трэкинга"
        backgroundColor: "#438dd5"
        color: "#ffffff"

  - id: "126"
    name: "BPM Second"
    subtitle: "[Deployment Node]"
    backgroundColor: "#ffffff"
    color: "#000000"

    children:
      - id: "127"
        name: "BPM"
        subtitle: "[Container: Camunda]"
        description: "Реализация сценариев трэкинга"
        backgroundColor: "#438dd5"
        color: "#ffffff"

  - id: "130"
    name: "Inventory server"
    subtitle: "[Deployment Node]"
    backgroundColor: "#ffffff"
    color: "#000000"

    children:
      - id: "131"
        name: "Inventory"
        subtitle: "[Container: go]"
        description: "Учет дронов"
        backgroundColor: "#438dd5"
        color: "#ffffff"

  - id: "134"
    name: "Tracker First"
    subtitle: "[Deployment Node]"
    backgroundColor: "#ffffff"
    color: "#000000"

    children:
      - id: "135"
        name: "Tracker"
        subtitle: "[Container: go]"
        description: "Подсистема трэкинга дронов в реальном времени"
        backgroundColor: "#438dd5"
        color: "#ffffff"

  - id: "139"
    name: "Tracker Second"
    subtitle: "[Deployment Node]"
    backgroundColor: "#ffffff"
    color: "#000000"

    children:
      - id: "140"
        name: "Tracker"
        subtitle: "[Container: go]"
        description: "Подсистема трэкинга дронов в реальном времени"
        backgroundColor: "#438dd5"
        color: "#ffffff"

  - id: "144"
    name: "Billing"
    subtitle: "[Deployment Node]"
    backgroundColor: "#ffffff"
    color: "#000000"

    children:
      - id: "145"
        name: "Billing"
        subtitle: "[Container: go]"
        description: "Прием оплат и контроль расходов"
        backgroundColor: "#438dd5"
        color: "#ffffff"

  - id: "95"
    name: "MainSystem"
    subtitle: "[Deployment Node]"
    backgroundColor: "#ffffff"
    color: "#000000"

    children:
      - id: "96"
        name: "Мобильный телохранитель"
        subtitle: "[Software System]"
        backgroundColor: "#dddddd"
        color: "#000000"

  - id: "97"
    name: "DroneNode1"
    subtitle: "[Deployment Node]"
    backgroundColor: "#ffffff"
    color: "#000000"

    children:
      - id: "98"
        name: "Дрон"
        subtitle: "[Software System]"
        description: "Автономный дрон"
        backgroundColor: "#c0c0c0"
        color: "#ffffff"

perspectives:
  - name: Static Structure
    relations:
      - from: "1"
        to: "5"
        label: "Управление услугой"
        color: "#707070"

      - from: "2"
        to: "5"
        label: "пополнение баланса"
        color: "#707070"

      - from: "3"
        to: "5"
        label: "Телеметрия"
        description: "MQTT"
        color: "#707070"

      - from: "5"
        to: "4"
        label: "Вызов службы охраны на проишествие"
        description: "REST"
        color: "#707070"

      - from: "5"
        to: "3"
        label: "Команды управления"
        description: "MQTT"
        color: "#707070"

      - from: "5"
        to: "2"
        label: "Оплата"
        color: "#707070"

      - from: "1"
        to: "6"
        label: "Управление услугой"
        color: "#707070"

      - from: "1"
        to: "7"
        label: "Управление услугой"
        color: "#707070"

      - from: "2"
        to: "21"
        label: "пополнение баланса"
        color: "#707070"

      - from: "3"
        to: "53"
        label: "Телеметрия"
        description: "MQTT"
        color: "#707070"

      - from: "3"
        to: "6"
        label: "Видео"
        description: "WebRTC"
        color: "#707070"

      - from: "3"
        to: "7"
        label: "Видео"
        description: "WebRTC"
        color: "#707070"

      - from: "11"
        to: "18"
        label: "Получение данных/ нотификаций/ выполнение запросов"
        description: "REST"
        color: "#707070"

      - from: "12"
        to: "18"
        label: "Получение данных/ нотификаций/ выполнение запросов"
        description: "REST"
        color: "#707070"

      - from: "15"
        to: "44"
        label: "получение профиля клиента по id"
        description: "REST"
        color: "#707070"

      - from: "18"
        to: "21"
        label: "Запрос баланса/осуществление платежа"
        description: "REST"
        color: "#707070"

      - from: "18"
        to: "38"
        label: "Запрос данных о свободных дронах/Резервация"
        description: "REST"
        color: "#707070"

      - from: "18"
        to: "44"
        label: "Запрос данных о клиенте и его детях"
        description: "REST"
        color: "#707070"

      - from: "18"
        to: "53"
        label: "Управление дроном"
        description: "REST"
        color: "#707070"

      - from: "21"
        to: "53"
        label: "Информирование об исчерпании средств на подписке"
        color: "#707070"

      - from: "53"
        to: "21"
        label: "Данные об использовании дрона"
        color: "#707070"

      - from: "53"
        to: "38"
        label: "Обновдение информации о дронах"
        description: "REST"
        color: "#707070"

      - from: "53"
        to: "4"
        label: "Вызов службы охраны на проишествие"
        description: "REST"
        color: "#707070"

      - from: "53"
        to: "3"
        label: "Команды управления"
        description: "MQTT"
        color: "#707070"

      - from: "6"
        to: "11"
        label: "Получение данных/ нотификаций/ выполнение запросов"
        description: "WebSocket"
        color: "#707070"

      - from: "6"
        to: "15"
        label: "Получение данных/нотификаций"
        description: "HTTP"
        color: "#707070"

      - from: "6"
        to: "2"
        label: "Оплата"
        color: "#707070"

      - from: "7"
        to: "2"
        label: "Оплата"
        color: "#707070"

      - from: "7"
        to: "12"
        label: "Получение данных/ нотификаций/ выполнение запросов"
        description: "WebSocket"
        color: "#707070"

      - from: "7"
        to: "15"
        label: "Получение данных/нотификаций"
        description: "HTTP"
        color: "#707070"

      - from: "2"
        to: "22"
        label: "пополнение баланса"
        color: "#707070"

      - from: "3"
        to: "56"
        label: "Телеметрия"
        description: "MQTT"
        color: "#707070"

      - from: "3"
        to: "56"
        label: "События безопасности"
        description: "MQTT"
        color: "#707070"

      - from: "15"
        to: "45"
        label: "получение профиля клиента по id"
        description: "REST"
        color: "#707070"

      - from: "15"
        to: "45"
        label: "ауктентификация клиента"
        description: "REST"
        color: "#707070"

      - from: "18"
        to: "22"
        label: "Запрос баланса/осуществление платежа"
        description: "REST"
        color: "#707070"

      - from: "18"
        to: "39"
        label: "Запрос данных о свободных дронах/Резервация"
        description: "REST"
        color: "#707070"

      - from: "18"
        to: "45"
        label: "Запрос данных о клиенте и его детях"
        description: "REST"
        color: "#707070"

      - from: "18"
        to: "54"
        label: "Управление дроном"
        description: "REST"
        color: "#707070"

      - from: "21"
        to: "54"
        label: "Информирование об исчерпании средств на подписке"
        color: "#707070"

      - from: "22"
        to: "23"
        label: "запрос остатка баланса"
        color: "#707070"

      - from: "22"
        to: "23"
        label: "списание баланса"
        color: "#707070"

      - from: "22"
        to: "23"
        label: "пополнение баланса"
        color: "#707070"

      - from: "24"
        to: "23"
        label: "списание баланса"
        color: "#707070"

      - from: "24"
        to: "54"
        label: "Информирование об исчерпании средств на подписке"
        color: "#707070"

      - from: "24"
        to: "53"
        label: "Информирование об исчерпании средств на подписке"
        color: "#707070"

      - from: "25"
        to: "26"
        label: "связь"
        description: "HTTP/REST"
        color: "#707070"

      - from: "25"
        to: "24"
        label: "учет использования дрона"
        color: "#707070"

      - from: "39"
        to: "40"
        label: "Запрос и обновление информации о дронах"
        color: "#707070"

      - from: "45"
        to: "46"
        label: "запрос/изменение данных о пользователях"
        color: "#707070"

      - from: "53"
        to: "25"
        label: "Данные об использовании дрона"
        color: "#707070"

      - from: "53"
        to: "22"
        label: "запрос остатка баланса"
        color: "#707070"

      - from: "53"
        to: "39"
        label: "Обновдение информации о дронах"
        description: "REST"
        color: "#707070"

      - from: "54"
        to: "55"
        label: "Запрос данных о статусе дрона"
        color: "#707070"

      - from: "54"
        to: "57"
        label: "Управление дроном"
        description: "REST"
        color: "#707070"

      - from: "56"
        to: "3"
        label: "Команды управления"
        description: "MQTT"
        color: "#707070"

      - from: "56"
        to: "57"
        label: "Телеметрия"
        description: "MQTT"
        color: "#707070"

      - from: "56"
        to: "57"
        label: "События безопасности"
        description: "MQTT"
        color: "#707070"

      - from: "57"
        to: "56"
        label: "Команды управления"
        description: "MQTT"
        color: "#707070"

      - from: "57"
        to: "55"
        label: "Обновление актуального статуса дронов"
        color: "#707070"

      - from: "57"
        to: "25"
        label: "Данные об использовании дрона"
        color: "#707070"

      - from: "57"
        to: "21"
        label: "Данные об использовании дрона"
        color: "#707070"

      - from: "57"
        to: "22"
        label: "запрос остатка баланса"
        color: "#707070"

      - from: "57"
        to: "39"
        label: "Обновдение информации о дронах"
        description: "REST"
        color: "#707070"

      - from: "57"
        to: "38"
        label: "Обновдение информации о дронах"
        description: "REST"
        color: "#707070"

      - from: "57"
        to: "4"
        label: "Вызов службы охраны на проишествие"
        description: "REST"
        color: "#707070"

  - name: Dynamic - Billing - Dynamic
    sequence:
- name: Deployment - ProductionDeployment
  relations:
    - from: "113"
      to: "117"
      label: "Получение данных/ нотификаций/ выполнение запросов"
      description: "WebSocket"
      color: "#707070"
    - from: "115"
      to: "120"
      label: "Получение данных/ нотификаций/ выполнение запросов"
      description: "WebSocket"
      color: "#707070"
    - from: "117"
      to: "123"
      label: "Получение данных/ нотификаций/ выполнение запросов"
      description: "REST"
      color: "#707070"
    - from: "117"
      to: "127"
      label: "Получение данных/ нотификаций/ выполнение запросов"
      description: "REST"
      color: "#707070"
    - from: "120"
      to: "123"
      label: "Получение данных/ нотификаций/ выполнение запросов"
      description: "REST"
      color: "#707070"
    - from: "120"
      to: "127"
      label: "Получение данных/ нотификаций/ выполнение запросов"
      description: "REST"
      color: "#707070"
    - from: "123"
      to: "131"
      label: "Запрос данных о свободных дронах/Резервация"
      description: "REST"
      color: "#707070"
    - from: "123"
      to: "135"
      label: "Управление дроном"
      description: "REST"
      color: "#707070"
    - from: "123"
      to: "140"
      label: "Управление дроном"
      description: "REST"
      color: "#707070"
    - from: "123"
      to: "145"
      label: "Запрос баланса/осуществление платежа"
      description: "REST"
      color: "#707070"
    - from: "127"
      to: "131"
      label: "Запрос данных о свободных дронах/Резервация"
      description: "REST"
      color: "#707070"
    - from: "127"
      to: "135"
      label: "Управление дроном"
      description: "REST"
      color: "#707070"
    - from: "127"
      to: "140"
      label: "Управление дроном"
      description: "REST"
      color: "#707070"
    - from: "127"
      to: "145"
      label: "Запрос баланса/осуществление платежа"
      description: "REST"
      color: "#707070"
    - from: "135"
      to: "131"
      label: "Обновдение информации о дронах"
      description: "REST"
      color: "#707070"
    - from: "135"
      to: "145"
      label: "Данные об использовании дрона"
      color: "#707070"
    - from: "140"
      to: "131"
      label: "Обновдение информации о дронах"
      description: "REST"
      color: "#707070"
    - from: "140"
      to: "145"
      label: "Данные об использовании дрона"
      color: "#707070"
    - from: "145"
      to: "140"
      label: "Информирование об исчерпании средств на подписке"
      color: "#707070"
    - from: "145"
      to: "135"
      label: "Информирование об исчерпании средств на подписке"
      color: "#707070"
- name: Deployment - TechnicalContext
  relations:
    - from: "102"
      to: "96"
      label: "Телеметрия"
      description: "MQTT"
      color: "#707070"
    - from: "109"
      to: "96"
      label: "пополнение баланса"
      color: "#707070"
    - from: "96"
      to: "98"
      label: "Команды управления"
      description: "MQTT"
      color: "#707070"
    - from: "96"
      to: "102"
      label: "Команды управления"
      description: "MQTT"
      color: "#707070"
    - from: "96"
      to: "106"
      label: "Вызов службы охраны на проишествие"
      description: "REST"
      color: "#707070"
    - from: "96"
      to: "109"
      label: "Оплата"
      color: "#707070"
    - from: "98"
      to: "96"
      label: "Телеметрия"
      description: "MQTT"
      color: "#707070"